# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

platform :ios do
  desc "Build iOS app without codesigning"
  lane :devbuild do
    ci_settings
    build_app(scheme: "Kiwix",
              destination: "generic/platform=iOS",
              sdk: 'iphoneos',
              skip_codesigning: true)
            end

  desc "Build iOS app for AppStore"
  lane :build do
    ci_settings
    get_certificates(
      development: true,
      api_key: app_store_connect_api_key(
          key_id: ENV['APP_STORE_CONNECT_API_KEY_KEY_ID'],
          issuer_id: ENV['APP_STORE_CONNECT_API_KEY_ISSUER_ID'],
          key_filepath: ENV['APP_STORE_CONNECT_API_KEY_KEY_FILEPATH'],
          duration: 1200, # optional (maximum 1200)
          in_house: false # optional but may be required if using match/sigh
        ),
      keychain_password: ENV['KEYCHAIN_PASSWORD'],
      platform: 'ios'
    )
    gym(
      destination: "generic/platform=iOS",
      sdk: 'iphoneos',
      configuration: 'Release',
      xcargs: "-allowProvisioningUpdates -authenticationKeyPath #{ENV['APP_STORE_CONNECT_API_KEY_KEY_FILEPATH']} -authenticationKeyID #{ENV['APP_STORE_CONNECT_API_KEY_KEY_ID']} -authenticationKeyIssuerID #{ENV['APP_STORE_CONNECT_API_KEY_ISSUER_ID']}",
      export_options: {
        method: "app-store"
      }
    )
  end

  lane :switch_manual do
    ci_settings
    match_certificates
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "Kiwix.xcodeproj",
      profile_name: "match AppStore self.Kiwix",
      code_sign_identity: "Apple Distribution",
      build_configurations: "Release"
    )
  end

  desc "Build iOS app for AppStore, manual signing"
  lane :build_manual do
    ci_settings
    match_certificates
    if is_ci
      unlock_keychain(
        path: "/Users/runner/Library/Keychains/fastlane_tmp_keychain-db",
        password: "my_temp_secret"
      )
    end
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "Kiwix.xcodeproj",
      profile_name: "match AppStore self.Kiwix",
      code_sign_identity: "Apple Distribution",
      build_configurations: "Release"
    )
    gym(
      destination: "generic/platform=iOS",
      sdk: 'iphoneos',
      configuration: 'Release',
      xcargs: "-allowProvisioningUpdates -authenticationKeyPath #{ENV['APP_STORE_CONNECT_API_KEY_KEY_FILEPATH']} -authenticationKeyID #{ENV['APP_STORE_CONNECT_API_KEY_KEY_ID']} -authenticationKeyIssuerID #{ENV['APP_STORE_CONNECT_API_KEY_ISSUER_ID']}",
      skip_profile_detection: true,
      export_options: {
        method: "app-store",
        skip_profile_detection: true,
        provisioningProfiles: {
          "self.Kiwix": "match AppStore self.Kiwix",
        },
        signingStyle: 'manual',
      }
    )
  end
end


platform :mac do
  desc "Build macOS app without codesigning"
  lane :devbuild do
    build_app(scheme: "Kiwix",
              destination: "generic/platform=macOS",
              skip_codesigning: true)
  end

  desc "Build macOS app for AppStore"
  lane :build do
    ci_settings
    match_certificates
    build_app(scheme: "Kiwix",
              destination: "generic/platform=macOS",
              export_options: {
        method: "app-store",
        provisioningProfiles: {
          "self.Kiwix": "match AppStore self.Kiwix",
        },
        signingStyle: 'manual',
      })
  end
end

private_lane :ci_settings do
  if is_ci
    setup_ci
    xcode_select "/Applications/Xcode_15.0.1.app"
  end
end

private_lane :match_certificates do
  ["development", "appstore"].each do |type|
    if is_ci
      match(type: type, readonly: true, git_url: "./certificates")
    else
      match(type: type, readonly: true)
    end
  end
end