# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

platform :ios do
  desc "Build the iOS app for development "
  lane :devbuild do
    match(type: "development", readonly: true)
    build_app(scheme: "Kiwix",
              destination: "generic/platform=iOS",
              sdk: 'iphoneos',
              export_options: {
                method: "development",
                signingStyle: 'manual',
                provisioningProfiles: {
                "self.Kiwix": "match Development self.Kiwix",
                }
              })
  end
end

platform :mac do
  desc "Build the macOS app for development"
  lane :devbuild do
    build_app(scheme: "Kiwix",
              destination: "generic/platform=macOS",
              export_options: {
                method: "development",
                signingStyle: 'manual'
              })
  end
end
