//
//  BookCellAccessory.swift
//  Kiwix
//
//  Created by Chris on 8/10/15.
//  Copyright (c) 2015 . All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class BookCellAccessoryDraw : NSObject {

    //// Drawing Methods
    
    public class func drawResumeIcon(size size: CGSize, color: UIColor) {
        //// Color Declarations
        //let color = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1.000)
        
        //// Frames
        let frame = CGRectMake(0, 0, size.width, size.height)
        
        
        //// Forma 1 Drawing
        let forma1Path = UIBezierPath()
        forma1Path.moveToPoint(CGPointMake(frame.minX + 21.28, frame.minY + 15.37))
        forma1Path.addLineToPoint(CGPointMake(frame.minX + 14.63, frame.minY + 10.54))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 13.8, frame.minY + 10.48), controlPoint1: CGPointMake(frame.minX + 14.39, frame.minY + 10.37), controlPoint2: CGPointMake(frame.minX + 14.07, frame.minY + 10.34))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 13.36, frame.minY + 11.19), controlPoint1: CGPointMake(frame.minX + 13.53, frame.minY + 10.61), controlPoint2: CGPointMake(frame.minX + 13.36, frame.minY + 10.89))
        forma1Path.addLineToPoint(CGPointMake(frame.minX + 13.36, frame.minY + 20.85))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 13.8, frame.minY + 21.56), controlPoint1: CGPointMake(frame.minX + 13.36, frame.minY + 21.15), controlPoint2: CGPointMake(frame.minX + 13.53, frame.minY + 21.43))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 14.16, frame.minY + 21.65), controlPoint1: CGPointMake(frame.minX + 13.91, frame.minY + 21.62), controlPoint2: CGPointMake(frame.minX + 14.04, frame.minY + 21.65))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 14.63, frame.minY + 21.49), controlPoint1: CGPointMake(frame.minX + 14.33, frame.minY + 21.65), controlPoint2: CGPointMake(frame.minX + 14.49, frame.minY + 21.6))
        forma1Path.addLineToPoint(CGPointMake(frame.minX + 21.28, frame.minY + 16.67))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 21.61, frame.minY + 16.02), controlPoint1: CGPointMake(frame.minX + 21.49, frame.minY + 16.51), controlPoint2: CGPointMake(frame.minX + 21.61, frame.minY + 16.27))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 21.28, frame.minY + 15.37), controlPoint1: CGPointMake(frame.minX + 21.61, frame.minY + 15.76), controlPoint2: CGPointMake(frame.minX + 21.48, frame.minY + 15.53))
        forma1Path.closePath()
        forma1Path.moveToPoint(CGPointMake(frame.minX + 16, frame.minY))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX, frame.minY + 16), controlPoint1: CGPointMake(frame.minX + 7.16, frame.minY), controlPoint2: CGPointMake(frame.minX, frame.minY + 7.16))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 16, frame.minY + 32), controlPoint1: CGPointMake(frame.minX, frame.minY + 24.84), controlPoint2: CGPointMake(frame.minX + 7.16, frame.minY + 32))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 32, frame.minY + 16), controlPoint1: CGPointMake(frame.minX + 24.84, frame.minY + 32), controlPoint2: CGPointMake(frame.minX + 32, frame.minY + 24.84))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 16, frame.minY), controlPoint1: CGPointMake(frame.minX + 32, frame.minY + 7.16), controlPoint2: CGPointMake(frame.minX + 24.84, frame.minY))
        forma1Path.closePath()
        forma1Path.moveToPoint(CGPointMake(frame.minX + 16, frame.minY + 30.45))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 1.65, frame.minY + 16), controlPoint1: CGPointMake(frame.minX + 8.64, frame.minY + 30.45), controlPoint2: CGPointMake(frame.minX + 1.65, frame.minY + 23.36))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 16, frame.minY + 1.65), controlPoint1: CGPointMake(frame.minX + 1.65, frame.minY + 8.64), controlPoint2: CGPointMake(frame.minX + 8.64, frame.minY + 1.65))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 30.45, frame.minY + 16), controlPoint1: CGPointMake(frame.minX + 23.36, frame.minY + 1.65), controlPoint2: CGPointMake(frame.minX + 30.45, frame.minY + 8.64))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 16, frame.minY + 30.45), controlPoint1: CGPointMake(frame.minX + 30.45, frame.minY + 23.36), controlPoint2: CGPointMake(frame.minX + 23.36, frame.minY + 30.45))
        forma1Path.closePath()
        color.setFill()
        forma1Path.fill()
    }

    public class func drawDownloadIcon(size size: CGSize, color: UIColor) {
        //// Color Declarations
        //let color = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1.000)

        //// Frames
        let frame = CGRectMake(0, 0, size.width, size.height)


        //// Forma 1 Drawing
        let forma1Path = UIBezierPath()
        forma1Path.moveToPoint(CGPointMake(frame.minX + 16, frame.minY))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX, frame.minY + 16), controlPoint1: CGPointMake(frame.minX + 7.16, frame.minY), controlPoint2: CGPointMake(frame.minX, frame.minY + 7.16))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 16, frame.minY + 32), controlPoint1: CGPointMake(frame.minX, frame.minY + 24.84), controlPoint2: CGPointMake(frame.minX + 7.16, frame.minY + 32))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 32, frame.minY + 16), controlPoint1: CGPointMake(frame.minX + 24.84, frame.minY + 32), controlPoint2: CGPointMake(frame.minX + 32, frame.minY + 24.84))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 16, frame.minY), controlPoint1: CGPointMake(frame.minX + 32, frame.minY + 7.16), controlPoint2: CGPointMake(frame.minX + 24.84, frame.minY))
        forma1Path.closePath()
        forma1Path.moveToPoint(CGPointMake(frame.minX + 16, frame.minY + 30.45))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 1.55, frame.minY + 16), controlPoint1: CGPointMake(frame.minX + 8.04, frame.minY + 30.45), controlPoint2: CGPointMake(frame.minX + 1.55, frame.minY + 23.96))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 16, frame.minY + 1.55), controlPoint1: CGPointMake(frame.minX + 1.55, frame.minY + 8.04), controlPoint2: CGPointMake(frame.minX + 8.04, frame.minY + 1.55))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 30.45, frame.minY + 16), controlPoint1: CGPointMake(frame.minX + 23.96, frame.minY + 1.55), controlPoint2: CGPointMake(frame.minX + 30.45, frame.minY + 8.04))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 16, frame.minY + 30.45), controlPoint1: CGPointMake(frame.minX + 30.45, frame.minY + 23.96), controlPoint2: CGPointMake(frame.minX + 23.96, frame.minY + 30.45))
        forma1Path.closePath()
        forma1Path.moveToPoint(CGPointMake(frame.minX + 22.24, frame.minY + 16.5))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 22.24, frame.minY + 17.59), controlPoint1: CGPointMake(frame.minX + 22.53, frame.minY + 16.8), controlPoint2: CGPointMake(frame.minX + 22.53, frame.minY + 17.3))
        forma1Path.addLineToPoint(CGPointMake(frame.minX + 16.54, frame.minY + 23.33))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 16.42, frame.minY + 23.41), controlPoint1: CGPointMake(frame.minX + 16.5, frame.minY + 23.37), controlPoint2: CGPointMake(frame.minX + 16.46, frame.minY + 23.41))
        forma1Path.addLineToPoint(CGPointMake(frame.minX + 16.38, frame.minY + 23.46))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 16.29, frame.minY + 23.5), controlPoint1: CGPointMake(frame.minX + 16.33, frame.minY + 23.46), controlPoint2: CGPointMake(frame.minX + 16.33, frame.minY + 23.5))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 16.21, frame.minY + 23.54), controlPoint1: CGPointMake(frame.minX + 16.25, frame.minY + 23.5), controlPoint2: CGPointMake(frame.minX + 16.25, frame.minY + 23.5))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 16.12, frame.minY + 23.54), controlPoint1: CGPointMake(frame.minX + 16.16, frame.minY + 23.54), controlPoint2: CGPointMake(frame.minX + 16.16, frame.minY + 23.54))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 15.95, frame.minY + 23.54), controlPoint1: CGPointMake(frame.minX + 16.08, frame.minY + 23.54), controlPoint2: CGPointMake(frame.minX + 16.03, frame.minY + 23.54))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 15.79, frame.minY + 23.54), controlPoint1: CGPointMake(frame.minX + 15.91, frame.minY + 23.54), controlPoint2: CGPointMake(frame.minX + 15.87, frame.minY + 23.54))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 15.7, frame.minY + 23.54), controlPoint1: CGPointMake(frame.minX + 15.74, frame.minY + 23.54), controlPoint2: CGPointMake(frame.minX + 15.74, frame.minY + 23.54))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 15.62, frame.minY + 23.5), controlPoint1: CGPointMake(frame.minX + 15.66, frame.minY + 23.54), controlPoint2: CGPointMake(frame.minX + 15.66, frame.minY + 23.54))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 15.53, frame.minY + 23.46), controlPoint1: CGPointMake(frame.minX + 15.57, frame.minY + 23.5), controlPoint2: CGPointMake(frame.minX + 15.57, frame.minY + 23.46))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 15.49, frame.minY + 23.41), controlPoint1: CGPointMake(frame.minX + 15.53, frame.minY + 23.46), controlPoint2: CGPointMake(frame.minX + 15.49, frame.minY + 23.46))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 15.36, frame.minY + 23.33), controlPoint1: CGPointMake(frame.minX + 15.45, frame.minY + 23.37), controlPoint2: CGPointMake(frame.minX + 15.4, frame.minY + 23.37))
        forma1Path.addLineToPoint(CGPointMake(frame.minX + 9.72, frame.minY + 17.55))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 9.72, frame.minY + 16.46), controlPoint1: CGPointMake(frame.minX + 9.42, frame.minY + 17.26), controlPoint2: CGPointMake(frame.minX + 9.42, frame.minY + 16.76))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 10.81, frame.minY + 16.46), controlPoint1: CGPointMake(frame.minX + 10.01, frame.minY + 16.17), controlPoint2: CGPointMake(frame.minX + 10.51, frame.minY + 16.17))
        forma1Path.addLineToPoint(CGPointMake(frame.minX + 15.25, frame.minY + 20.9))
        forma1Path.addLineToPoint(CGPointMake(frame.minX + 15.25, frame.minY + 8.63))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 16, frame.minY + 7.88), controlPoint1: CGPointMake(frame.minX + 15.25, frame.minY + 8.21), controlPoint2: CGPointMake(frame.minX + 15.58, frame.minY + 7.88))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 16.75, frame.minY + 8.63), controlPoint1: CGPointMake(frame.minX + 16.42, frame.minY + 7.88), controlPoint2: CGPointMake(frame.minX + 16.75, frame.minY + 8.21))
        forma1Path.addLineToPoint(CGPointMake(frame.minX + 16.75, frame.minY + 20.9))
        forma1Path.addLineToPoint(CGPointMake(frame.minX + 21.11, frame.minY + 16.54))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 22.24, frame.minY + 16.5), controlPoint1: CGPointMake(frame.minX + 21.44, frame.minY + 16.21), controlPoint2: CGPointMake(frame.minX + 21.95, frame.minY + 16.21))
        forma1Path.closePath()
        color.setFill()
        forma1Path.fill()
    }

    public class func drawCrossIcon(size size: CGSize, color: UIColor) {
        //// Color Declarations
        //let color = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1.000)

        //// Frames
        let frame = CGRectMake(0, 0, size.width, size.height)


        //// Forma 1 Drawing
        let forma1Path = UIBezierPath()
        forma1Path.moveToPoint(CGPointMake(frame.minX + 16, frame.minY))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX, frame.minY + 16), controlPoint1: CGPointMake(frame.minX + 7.16, frame.minY), controlPoint2: CGPointMake(frame.minX, frame.minY + 7.16))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 16, frame.minY + 32), controlPoint1: CGPointMake(frame.minX, frame.minY + 24.84), controlPoint2: CGPointMake(frame.minX + 7.16, frame.minY + 32))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 32, frame.minY + 16), controlPoint1: CGPointMake(frame.minX + 24.84, frame.minY + 32), controlPoint2: CGPointMake(frame.minX + 32, frame.minY + 24.84))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 16, frame.minY), controlPoint1: CGPointMake(frame.minX + 32, frame.minY + 7.16), controlPoint2: CGPointMake(frame.minX + 24.84, frame.minY))
        forma1Path.closePath()
        forma1Path.moveToPoint(CGPointMake(frame.minX + 16, frame.minY + 30.45))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 1.55, frame.minY + 16), controlPoint1: CGPointMake(frame.minX + 8.27, frame.minY + 30.45), controlPoint2: CGPointMake(frame.minX + 1.55, frame.minY + 23.73))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 16, frame.minY + 1.55), controlPoint1: CGPointMake(frame.minX + 1.55, frame.minY + 8.27), controlPoint2: CGPointMake(frame.minX + 8.27, frame.minY + 1.55))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 30.45, frame.minY + 16), controlPoint1: CGPointMake(frame.minX + 23.73, frame.minY + 1.55), controlPoint2: CGPointMake(frame.minX + 30.45, frame.minY + 8.27))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 16, frame.minY + 30.45), controlPoint1: CGPointMake(frame.minX + 30.45, frame.minY + 23.73), controlPoint2: CGPointMake(frame.minX + 23.73, frame.minY + 30.45))
        forma1Path.closePath()
        forma1Path.moveToPoint(CGPointMake(frame.minX + 22.71, frame.minY + 9.28))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 21.33, frame.minY + 9.28), controlPoint1: CGPointMake(frame.minX + 22.33, frame.minY + 8.9), controlPoint2: CGPointMake(frame.minX + 21.71, frame.minY + 8.9))
        forma1Path.addLineToPoint(CGPointMake(frame.minX + 16, frame.minY + 14.62))
        forma1Path.addLineToPoint(CGPointMake(frame.minX + 10.67, frame.minY + 9.28))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 9.28, frame.minY + 9.28), controlPoint1: CGPointMake(frame.minX + 10.28, frame.minY + 8.9), controlPoint2: CGPointMake(frame.minX + 9.67, frame.minY + 8.9))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 9.28, frame.minY + 10.67), controlPoint1: CGPointMake(frame.minX + 8.9, frame.minY + 9.67), controlPoint2: CGPointMake(frame.minX + 8.9, frame.minY + 10.28))
        forma1Path.addLineToPoint(CGPointMake(frame.minX + 14.62, frame.minY + 16))
        forma1Path.addLineToPoint(CGPointMake(frame.minX + 9.29, frame.minY + 21.33))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 9.29, frame.minY + 22.71), controlPoint1: CGPointMake(frame.minX + 8.9, frame.minY + 21.71), controlPoint2: CGPointMake(frame.minX + 8.9, frame.minY + 22.33))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 10.67, frame.minY + 22.71), controlPoint1: CGPointMake(frame.minX + 9.67, frame.minY + 23.1), controlPoint2: CGPointMake(frame.minX + 10.29, frame.minY + 23.1))
        forma1Path.addLineToPoint(CGPointMake(frame.minX + 16, frame.minY + 17.38))
        forma1Path.addLineToPoint(CGPointMake(frame.minX + 21.33, frame.minY + 22.71))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 22.71, frame.minY + 22.71), controlPoint1: CGPointMake(frame.minX + 21.71, frame.minY + 23.1), controlPoint2: CGPointMake(frame.minX + 22.33, frame.minY + 23.1))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 22.71, frame.minY + 21.33), controlPoint1: CGPointMake(frame.minX + 23.1, frame.minY + 22.33), controlPoint2: CGPointMake(frame.minX + 23.1, frame.minY + 21.71))
        forma1Path.addLineToPoint(CGPointMake(frame.minX + 17.38, frame.minY + 16))
        forma1Path.addLineToPoint(CGPointMake(frame.minX + 22.71, frame.minY + 10.67))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 22.71, frame.minY + 9.28), controlPoint1: CGPointMake(frame.minX + 23.1, frame.minY + 10.28), controlPoint2: CGPointMake(frame.minX + 23.1, frame.minY + 9.67))
        forma1Path.closePath()
        color.setFill()
        forma1Path.fill()
    }

    public class func drawPauseIcon(size size: CGSize, color: UIColor) {
        //// Color Declarations
        //let color = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1.000)

        //// Frames
        let frame = CGRectMake(0, 0, size.width, size.height)


        //// Forma 1 Drawing
        let forma1Path = UIBezierPath()
        forma1Path.moveToPoint(CGPointMake(frame.minX + 16, frame.minY + 32))
        forma1Path.addCurveToPoint(CGPointMake(-0, 16), controlPoint1: CGPointMake(frame.minX + 7.18, frame.minY + 32), controlPoint2: CGPointMake(-0, 24.82))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 16, frame.minY), controlPoint1: CGPointMake(-0, 7.18), controlPoint2: CGPointMake(frame.minX + 7.18, frame.minY))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 32, frame.minY + 16), controlPoint1: CGPointMake(frame.minX + 24.82, frame.minY), controlPoint2: CGPointMake(frame.minX + 32, frame.minY + 7.18))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 16, frame.minY + 32), controlPoint1: CGPointMake(frame.minX + 32, frame.minY + 24.82), controlPoint2: CGPointMake(frame.minX + 24.82, frame.minY + 32))
        forma1Path.closePath()
        forma1Path.moveToPoint(CGPointMake(frame.minX + 16, frame.minY + 1.55))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 1.55, frame.minY + 16), controlPoint1: CGPointMake(frame.minX + 8.24, frame.minY + 1.55), controlPoint2: CGPointMake(frame.minX + 1.55, frame.minY + 8.25))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 16, frame.minY + 30.45), controlPoint1: CGPointMake(frame.minX + 1.55, frame.minY + 23.76), controlPoint2: CGPointMake(frame.minX + 8.24, frame.minY + 30.45))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 30.45, frame.minY + 16), controlPoint1: CGPointMake(frame.minX + 23.75, frame.minY + 30.45), controlPoint2: CGPointMake(frame.minX + 30.45, frame.minY + 23.75))
        forma1Path.addCurveToPoint(CGPointMake(frame.minX + 16, frame.minY + 1.55), controlPoint1: CGPointMake(frame.minX + 30.45, frame.minY + 8.25), controlPoint2: CGPointMake(frame.minX + 23.75, frame.minY + 1.55))
        forma1Path.closePath()
        forma1Path.moveToPoint(CGPointMake(frame.minX + 17.61, frame.minY + 9.95))
        forma1Path.addLineToPoint(CGPointMake(frame.minX + 19.54, frame.minY + 9.95))
        forma1Path.addLineToPoint(CGPointMake(frame.minX + 19.54, frame.minY + 22.32))
        forma1Path.addLineToPoint(CGPointMake(frame.minX + 17.61, frame.minY + 22.32))
        forma1Path.addLineToPoint(CGPointMake(frame.minX + 17.61, frame.minY + 9.95))
        forma1Path.closePath()
        forma1Path.moveToPoint(CGPointMake(frame.minX + 12.46, frame.minY + 9.95))
        forma1Path.addLineToPoint(CGPointMake(frame.minX + 14.39, frame.minY + 9.95))
        forma1Path.addLineToPoint(CGPointMake(frame.minX + 14.39, frame.minY + 22.32))
        forma1Path.addLineToPoint(CGPointMake(frame.minX + 12.46, frame.minY + 22.32))
        forma1Path.addLineToPoint(CGPointMake(frame.minX + 12.46, frame.minY + 9.95))
        forma1Path.closePath()
        color.setFill()
        forma1Path.fill()
    }

}

@objc protocol StyleKitSettableImage {
    func setImage(image: UIImage!)
}

@objc protocol StyleKitSettableSelectedImage {
    func setSelectedImage(image: UIImage!)
}
